Repository WindowsMeosu/peppypedia-old, pull requests merged in 2022-10, with the labels that each got.

#8 Create .editorconfig
  .editorconfig
Labels: jekyll related

#10 merge master to testing
  .editorconfig
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/page-additions.md
  .github/ISSUE_TEMPLATE/post-request.md
  .github/workflows/cache.yml
  CODE_OF_CONDUCT.md
  _posts/maps:Disco Prince.md
Labels: testing

#15 Create _config.yml
  _config.yml
Labels: jekyll related

#17 Merge pull request #13 from gitMiloTilo/testing
  _includes/navigation.html
  _layouts/default.html
Labels: jekyll related, testing

#25 Merge pull request #23 from gitMiloTilo/master
  .github/workflows/pages.yml
Labels: testing

#26 Merge pull request #25 from gitMiloTilo/testing
  about.md
Labels: _posts, jekyll related, testing

#30 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: enhancement, testing

#31 add posts
  _posts/2007-08-28-users:peppy.md
  _posts/2007-10-06-maps:disco-prince.md
Labels: _posts

#28 posts
  _layouts/home.html
  _layouts/page.html
  _layouts/post.html
Labels: enhancement, _posts, jekyll related, testing, scss

#33 Fix syntax + other stuff
  _posts/2007-08-28-users:peppy.md
  package.json
Labels: documentation, _posts, testing

#34 merge everything to testing
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/irc.yml
  .github/workflows/osu!profile.yml
  README.md
  _config.yml
  _includes/disquis_comments.html
  _layouts/default.html
  _layouts/page.html
  _posts/2007-08-28-users:peppy.md
  _posts/2007-10-06-maps:Disco Prince.md
  about.md
  changelog.md
  package.json
Labels: testing

#35 more workflows
  .github/workflows/first-interaction.yml
  .github/workflows/manual.yml
  .github/workflows/stale.yml
Labels: help wanted, good first issue, testing

#37 Merge pull request #34 from gitMiloTilo/master
  .github/workflows/first-interaction.yml
  .github/workflows/manual.yml
  .github/workflows/stale.yml
Labels: testing

#42 e
  _includes/dialog.tsx
  assets/_posts.tsx
  assets/css/style.scss
  database/users/users.ts
  index.ts
  src/providers/AuthContext.tsx
  src/providers/ConfirmDialogContext.tsx
  src/types/oauth_access_token.ts
  src/types/users.ts
Labels: documentation, enhancement, priority:2

#44 q
  _layouts/create-account.html
  _layouts/create.html
  _layouts/dialog.tsx
  _layouts/login.html
  _layouts/user-profile.html
Labels: enhancement, priority:1

#45 merge
  _layouts/create-account.html
  _layouts/create.html
  _layouts/dialog.tsx
  _layouts/login.html
  _layouts/user-profile.html
  changelog.md
  readme.md
Labels: testing
